global_defs {
        router_id haproxy1
        enable_script_security
        script_user root
}

vrrp_script chk_nginx {
        script "/etc/keepalived/check_nginx.sh"
        interval 2
        timeout 1
        fall 3
        rise 2
        weight -80
}

vrrp_instance VI_1 {
        state BACKUP
        interface enp6s18
        virtual_router_id 33
        priority 200
        advert_int 1

        nopreempt

        unicast_src_ip 192.168.50.9
        unicast_peer {
                192.168.50.121
        }

        authentication {
                auth_type PASS
                auth_pass Change33
        }

        track_script {
                chk_nginx
        }

        virtual_ipaddress {
                192.168.50.20/24 dev enp6s18
        }
}
